/*
 * Copyright 2014-2016 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define KAA_BUILD_VERSION             "0.10.0"
# define KAA_BUILD_COMMIT_HASH         ""

# define KAA_SDK_TOKEN                 "DKMQnKGTk6PPyOh_5MU_KNVs7Uk"

# define KAA_PROFILE_SCHEMA_VERSION    0


# define KAA_SYNC_TIMEOUT               60000L


/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x929a2016,
            321,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -52 , -7 , 14 , 48 , -127 , 46 , -104 , 44 , 110 , 6 , 105 , 112 , 52 , -72 , 40 , -54 , 86 , 105 , 35 , 38 , -37 , -94 , 34 , 0 , -51 , 98 , -32 , 30 , -58 , -92 , 113 , -78 , 101 , -112 , 38 , -72 , -92 , -56 , 20 , -81 , 25 , -118 , 84 , 12 , 5 , 106 , 120 , -106 , 40 , 10 , 64 , -66 , -70 , -6 , -112 , -5 , 56 , -119 , 14 , 62 , -14 , -72 , 43 , -108 , 23 , -40 , -28 , -79 , -128 , 17 , 106 , 118 , 92 , -25 , -59 , -29 , -112 , -62 , -31 , -28 , 13 , -3 , -50 , -57 , 8 , 71 , 103 , -117 , -20 , 12 , -53 , -90 , -26 , -9 , -65 , -5 , 13 , 104 , -116 , -112 , -94 , -78 , -87 , -32 , -116 , -115 , 47 , -68 , -9 , 31 , -94 , 13 , -56 , 72 , 22 , 69 , -71 , 64 , 10 , 1 , -116 , 97 , -127 , 24 , -5 , 38 , 114 , 44 , 59 , 21 , -95 , -52 , 38 , 65 , -82 , -56 , 44 , 126 , 83 , -34 , 18 , -111 , 13 , -108 , -47 , 30 , 125 , -31 , -40 , -74 , -107 , -104 , -53 , 55 , -12 , 14 , 91 , 62 , -49 , 32 , -18 , 95 , 4 , 29 , -108 , -89 , 76 , 6 , 31 , 83 , -95 , -37 , -63 , -77 , -110 , -67 , 21 , -74 , -29 , 85 , -73 , 23 , -27 , 94 , -119 , 74 , 58 , -40 , -88 , -7 , -124 , -76 , -55 , -60 , 49 , -95 , 92 , -37 , -114 , -63 , 94 , 125 , -72 , 44 , -63 , -74 , -68 , 122 , 110 , 69 , -83 , 87 , 87 , -79 , 51 , 98 , -21 , 46 , 115 , -2 , -53 , -7 , 105 , 8 , -107 , 15 , 101 , -21 , 39 , 16 , -93 , -93 , -89 , 114 , -22 , 22 , -80 , -113 , -112 , 88 , -8 , 59 , -4 , -104 , 73 , 42 , -44 , -81 , 84 , 73 , 78 , 40 , 49 , 13 , -59 , 105 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 15 , 49 , 57 , 50 , 46 , 49 , 54 , 56 , 46 , 49 , 48 , 48 , 46 , 49 , 56 , 49 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x929a2016,
            321,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -52 , -7 , 14 , 48 , -127 , 46 , -104 , 44 , 110 , 6 , 105 , 112 , 52 , -72 , 40 , -54 , 86 , 105 , 35 , 38 , -37 , -94 , 34 , 0 , -51 , 98 , -32 , 30 , -58 , -92 , 113 , -78 , 101 , -112 , 38 , -72 , -92 , -56 , 20 , -81 , 25 , -118 , 84 , 12 , 5 , 106 , 120 , -106 , 40 , 10 , 64 , -66 , -70 , -6 , -112 , -5 , 56 , -119 , 14 , 62 , -14 , -72 , 43 , -108 , 23 , -40 , -28 , -79 , -128 , 17 , 106 , 118 , 92 , -25 , -59 , -29 , -112 , -62 , -31 , -28 , 13 , -3 , -50 , -57 , 8 , 71 , 103 , -117 , -20 , 12 , -53 , -90 , -26 , -9 , -65 , -5 , 13 , 104 , -116 , -112 , -94 , -78 , -87 , -32 , -116 , -115 , 47 , -68 , -9 , 31 , -94 , 13 , -56 , 72 , 22 , 69 , -71 , 64 , 10 , 1 , -116 , 97 , -127 , 24 , -5 , 38 , 114 , 44 , 59 , 21 , -95 , -52 , 38 , 65 , -82 , -56 , 44 , 126 , 83 , -34 , 18 , -111 , 13 , -108 , -47 , 30 , 125 , -31 , -40 , -74 , -107 , -104 , -53 , 55 , -12 , 14 , 91 , 62 , -49 , 32 , -18 , 95 , 4 , 29 , -108 , -89 , 76 , 6 , 31 , 83 , -95 , -37 , -63 , -77 , -110 , -67 , 21 , -74 , -29 , 85 , -73 , 23 , -27 , 94 , -119 , 74 , 58 , -40 , -88 , -7 , -124 , -76 , -55 , -60 , 49 , -95 , 92 , -37 , -114 , -63 , 94 , 125 , -72 , 44 , -63 , -74 , -68 , 122 , 110 , 69 , -83 , 87 , 87 , -79 , 51 , 98 , -21 , 46 , 115 , -2 , -53 , -7 , 105 , 8 , -107 , 15 , 101 , -21 , 39 , 16 , -93 , -93 , -89 , 114 , -22 , 22 , -80 , -113 , -112 , 88 , -8 , 59 , -4 , -104 , 73 , 42 , -44 , -81 , 84 , 73 , 78 , 40 , 49 , 13 , -59 , 105 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 15 , 49 , 57 , 50 , 46 , 49 , 54 , 56 , 46 , 49 , 48 , 48 , 46 , 49 , 56 , 49 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    1

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
10 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

